# This flake was initially generated by fh, the CLI for FlakeHub (version 0.1.25)
{
  # A helpful description of your flake
  description = "Productive Emacs config";

  # Flake inputs
  inputs = {
    flake-schemas.url = "https://flakehub.com/f/DeterminateSystems/flake-schemas/*";
    nixpkgs.url = "https://flakehub.com/f/NixOS/nixpkgs/0.1.*";
    treefmt-nix = {
      url = "https://flakehub.com/f/numtide/treefmt-nix/0.1.*";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    home-manager = {
      url = "https://flakehub.com/f/nix-community/home-manager/0.1.*";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nmt = {
      url = "sourcehut:~rycee/nmt";
      flake = false;
    };
    emacs-overlay = {
      # Pinned for reproducibility - update periodically with 'nix flake lock --update-input emacs-overlay'
      url = "github:nix-community/emacs-overlay/9e2937bba3c9bf92f0249591f332780de8f290ef";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nix-emacs-ci = {
      url = "github:purcell/nix-emacs-ci";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  # Flake outputs that other flakes can use
  outputs =
    {
      self,
      flake-schemas,
      nixpkgs,
      treefmt-nix,
      home-manager,
      emacs-overlay,
      nix-emacs-ci,
      ...
    }:
    let
      # Helpers for producing system-specific outputs
      supportedSystems = [
        "x86_64-linux"
        "aarch64-darwin"
        "x86_64-darwin"
        "aarch64-linux"
      ];
      forEachSupportedSystem =
        f:
        nixpkgs.lib.genAttrs supportedSystems (
          system:
          f {
            pkgs = import nixpkgs {
              inherit system;
              overlays = [ emacs-overlay.overlays.default ];
            };
          }
        );

      treeconfig = {
        projectRootFile = "flake.nix";
        programs = {
          nixfmt.enable = true;
          yamlfmt.enable = true;
          actionlint.enable = true;
          deadnix.enable = true;
          statix.enable = true;
        };
      };
      treefmtEval = forEachSupportedSystem ({ pkgs }: treefmt-nix.lib.evalModule pkgs treeconfig);
    in
    {
      # Schemas tell Nix about the structure of your flake's outputs
      inherit (flake-schemas) schemas;
      packages = forEachSupportedSystem (
        { pkgs, ... }:
        rec {
          default = emacs;
          emacs = pkgs.callPackage ./default.nix { };
          config = pkgs.callPackage ./config.nix { };

        }
      );
      formatter = forEachSupportedSystem ({ pkgs }: treefmtEval.${pkgs.system}.config.build.wrapper);

      homeModules.default = ./module.nix;

      overlays.default = final: _prev: {
        jotain = final.callPackage ./default.nix { };
        jotain-config = final.callPackage ./config.nix { };
      };

      checks = forEachSupportedSystem (
        { pkgs }:
        let
          emacsPackage = pkgs.callPackage ./default.nix { };
          # TODO: Update NMT tests for new module structure
          # nmtTests = import ./nmt-tests {
          #   inherit pkgs home-manager;
          #   homeModule = self.homeModules.default;
          #   inherit emacsPackage;
          # };
          # runtimeTests = import ./nmt-tests/runtime.nix {
          #   inherit pkgs home-manager;
          #   homeModule = self.homeModules.default;
          #   inherit emacsPackage;
          # };
        in
        {
          # Fast checks (run by default)
          # ===========================

          # Formatting check
          formatting = treefmtEval.${pkgs.system}.config.build.check self;

          # Fast binary smoke test - just checks binary exists and starts
          binary-smoke-test = pkgs.runCommand "emacs-binary-smoke-test" { } ''
            # Test 1: Emacs binary exists and is executable
            test -x ${self.packages.${pkgs.system}.emacs}/bin/emacs
            echo "PASS: Emacs binary is executable"

            # Test 2: Emacs starts without errors
            ${self.packages.${pkgs.system}.emacs}/bin/emacs --batch --eval '(message "Smoke test: OK")'
            echo "PASS: Emacs starts successfully"

            touch $out
          '';

          # ERT test tiers (from fastest to slowest)
          smoke-tests = emacsPackage.passthru.smoke-test; # < 1 second
          inherit (emacsPackage.passthru) fast-tests; # < 5 seconds
          emacs-tests = emacsPackage.passthru.tests; # Full suite
        }
        // nmtTests
        # Runtime tests available separately via:
        # nix build .#checks.<system>.test-emacs-runtime
        # CI runs them automatically when CI env var is set
        // (pkgs.lib.optionalAttrs (builtins.getEnv "CI" != "") runtimeTests)
      );

      # Development environments
      devShells = forEachSupportedSystem (
        { pkgs }:
        {
          default = pkgs.mkShell {
            # Pinned packages available in the environment
            packages = with pkgs; [
              nixpkgs-fmt
              just
              deadnix
              statix
              git
              (ripgrep.override { withPCRE2 = true; }) # PCRE2 support for advanced search
              (pkgs.callPackage ./default.nix { }) # Legacy for comparison
            ];

            shellHook = ''
              # Create isolated development environment
              export DEV_HOME="$PWD/.dev-home"
              mkdir -p "$DEV_HOME"/{.config,.cache,.local/share}

              # Isolate Emacs from user's home directory
              export HOME="$DEV_HOME"
              export XDG_CONFIG_HOME="$DEV_HOME/.config"
              export XDG_CACHE_HOME="$DEV_HOME/.cache"
              export XDG_DATA_HOME="$DEV_HOME/.local/share"

              # Set DOOMDIR for doom CLI
              export DOOMDIR="$PWD/doomdir"

              # Detect Emacs version at runtime
              export EMACS="${doomEmacsPkg}/bin/doom-emacs"
              if command -v "$EMACS" >/dev/null 2>&1; then
                export EMACSVERSION="$($EMACS --no-site-file --batch --eval '(princ emacs-version)' 2>/dev/null || echo 'unknown')"
              else
                export EMACSVERSION="unknown"
              fi

              echo "Jotain Emacs Development Environment (ISOLATED)"
              echo "================================================"
              echo "🔒 Isolated environment active!"
              echo "   Emacs version: $EMACSVERSION"
              echo "   HOME: $HOME"
              echo "   DOOMDIR: $DOOMDIR"
              echo "   Your personal Emacs config is protected"
              echo ""
              echo "Available commands:"
              echo "  doom-emacs     - Launch Jotain Emacs"
              echo "  doom sync      - Synchronize configuration"
              echo "  doom doctor    - Check health"
              echo "  just           - Show all available commands"
              echo "  just build     - Build Jotain Emacs package"
              echo "  just check     - Quick syntax check"
              echo ""
              echo "Code quality tools:"
              echo "  nix fmt        - Format and check Nix files"
              echo "  deadnix .      - Find dead Nix code"
              echo "  statix check . - Find Nix anti-patterns"
              echo "  rg             - ripgrep with PCRE2 support"
              echo ""
              echo "⚠️  Note: This shell uses isolated HOME directory"
              echo "   Changes won't affect your personal Emacs setup"
              echo ""
              echo "💡 Tip: Run 'nix flake update' to update Jotain Emacs and packages"
            '';
          };

          # CI shell using minimal nix-emacs-ci build for faster testing
          ci = pkgs.mkShell {
            # Minimal packages for CI testing
            packages = with pkgs; [
              just
              git
              (ripgrep.override { withPCRE2 = true; })
              # Use nix-emacs-ci's minimal Emacs 30 build
              nix-emacs-ci.packages.${pkgs.system}."emacs-30-2"
              doomEmacsPkg # Still need doom CLI
            ];

            shellHook = ''
              # Create isolated CI environment
              export DEV_HOME="$PWD/.ci-home"
              mkdir -p "$DEV_HOME"/{.config,.cache,.local/share}

              # Isolate Emacs from user's home directory
              export HOME="$DEV_HOME"
              export XDG_CONFIG_HOME="$DEV_HOME/.config"
              export XDG_CACHE_HOME="$DEV_HOME/.cache"
              export XDG_DATA_HOME="$DEV_HOME/.local/share"

              # Set DOOMDIR for doom CLI
              export DOOMDIR="$PWD/doomdir"

              # Use CI Emacs build
              export EMACS="${nix-emacs-ci.packages.${pkgs.system}."emacs-30-2"}/bin/emacs"
              if command -v "$EMACS" >/dev/null 2>&1; then
                export EMACSVERSION="$($EMACS --no-site-file --batch --eval '(princ emacs-version)' 2>/dev/null || echo 'unknown')"
              else
                export EMACSVERSION="unknown"
              fi

              echo "CI Environment (nix-emacs-ci)"
              echo "=============================="
              echo "   Emacs version: $EMACSVERSION (minimal build)"
              echo "   HOME: $HOME"
              echo "   DOOMDIR: $DOOMDIR"
              echo ""
              echo "This is a minimal CI environment for fast testing."
              echo "Use 'nix develop' for full development environment."
            '';
          };
        }
      );
    };
}
